"use client";

import { Separator } from "@/components/ui/separator";
import { formatDate } from "@/lib/format";
import { WIDGET_REGISTRY } from "@/modules/newspaper/lib/widgets/registry";
import type { EditionBlock } from "@/modules/newspaper/lib/widgets/types";

interface Edition {
  id: string;
  title: string;
  content: EditionBlock[];
  generated_at: string;
}

const FONT_FAMILY_CLASS: Record<string, string> = {
  serif: "font-serif",
  sans: "font-sans",
  mono: "font-mono",
};

const FONT_SIZE_CLASS: Record<string, string> = {
  sm: "text-sm",
  md: "text-base",
  lg: "text-lg",
};

const LINE_HEIGHT_CLASS: Record<string, string> = {
  normal: "leading-normal",
  relaxed: "leading-relaxed",
  loose: "leading-loose",
};

export function NewspaperPreview({
  edition,
  printConfig = {},
}: {
  edition: Edition;
  printConfig?: Record<string, string>;
}) {
  const fontClass = FONT_FAMILY_CLASS[printConfig.font_family ?? "serif"] ?? "font-serif";
  const sizeClass = FONT_SIZE_CLASS[printConfig.font_size ?? "md"] ?? "text-base";
  const leadingClass = LINE_HEIGHT_CLASS[printConfig.line_height ?? "relaxed"] ?? "leading-relaxed";
  const twoCol = (printConfig.columns ?? "1") === "2";

  return (
    <div className={`mx-auto max-w-2xl bg-white dark:bg-card print:bg-white print:text-black print:max-w-none ${fontClass} ${sizeClass} ${leadingClass}`}>
      <div className="border-b-4 border-double border-black dark:border-foreground py-6 text-center print:border-black">
        <h1 className="text-4xl font-bold font-serif">{edition.title}</h1>
        <p className="mt-1 text-sm text-muted-foreground print:text-gray-600">
          {formatDate(edition.generated_at)}
        </p>
      </div>

      <div
        className="py-4"
        style={twoCol ? { columnCount: 2, columnGap: "2.5rem" } : undefined}
      >
        {edition.content.map((block, i) => {
          const widget = WIDGET_REGISTRY[block.type];
          if (!widget) return null;
          const Preview = widget.previewComponent;
          return (
            <div
              key={i}
              className={twoCol ? "pb-6 mb-4 break-inside-avoid" : "py-4 border-b"}
              style={twoCol ? { breakInside: "avoid", pageBreakInside: "avoid" } : undefined}
            >
              <Preview block={block} />
            </div>
          );
        })}
      </div>

      {edition.content.length === 0 && (
        <p className="py-8 text-center text-muted-foreground">
          This edition has no content blocks.
        </p>
      )}

      <Separator />
      <p className="py-4 text-center text-xs text-muted-foreground">
        Generated by Memento
      </p>
    </div>
  );
}
